# Generated by Django 3.2 on 2021-04-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registracni_znacka', models.CharField(max_length=100)),
                ('znacka_auta', models.CharField(max_length=100)),
                ('typ_auta', models.CharField(max_length=100)),
                ('najeto_v_km', models.IntegerField()),
                ('datum_STK', models.DateTimeField()),
            ],
        ),
    ]
