# Generated by Django 3.2 on 2021-05-07 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_zakaznik'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='vypujcka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.vypujcka'),
        ),
        migrations.AddField(
            model_name='zakaznik',
            name='vypujcka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.vypujcka'),
        ),
    ]
