# Generated by Django 3.2 on 2021-05-07 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0004_auto_20210507_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='vypujcka',
        ),
        migrations.RemoveField(
            model_name='zakaznik',
            name='vypujcka',
        ),
        migrations.AddField(
            model_name='vypujcka',
            name='auto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.auto'),
        ),
        migrations.AddField(
            model_name='vypujcka',
            name='zakaznik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.zakaznik'),
        ),
    ]
