# Generated by Django 3.2 on 2021-05-08 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0005_auto_20210507_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registracni_znacka', models.CharField(max_length=100)),
                ('znacka_auta', models.CharField(max_length=100)),
                ('typ_auta', models.CharField(max_length=100)),
                ('najeto_v_km', models.IntegerField()),
                ('datum_STK', models.DateField()),
                ('auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.auto')),
            ],
        ),
    ]
