# Generated by Django 3.2 on 2021-05-08 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0006_formularauto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularauto',
            name='auto',
        ),
        migrations.CreateModel(
            name='FormularVypujcka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('cislo_rp', models.CharField(max_length=100)),
                ('datum_narozeni', models.DateField()),
                ('zahajeni_vypujcky', models.DateTimeField()),
                ('konec_vypujcky', models.DateTimeField()),
                ('auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.auto')),
            ],
        ),
    ]
